# Generated by Django 4.2.25 on 2025-10-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='tags',
            field=models.TextField(default='[]', verbose_name='标签'),
        ),
    ]
